services:
  - type: web
    name: youtube-extract-service
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: "8080"
      - key: YT_EXTRACT_API_KEY
        sync: false
      - key: YT_COOKIES_B64
        sync: false
    healthCheckPath: /health
    autoDeploy: true
